# Generated by Django 3.2 on 2023-11-29 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231116_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_all',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('APPLE', 'apple'), ('SAMSUNG', 'samsung'), ('XIAOMI', 'xiaomi'), ('HUAWEI', 'huawei'), ('GOOGLE', 'google'), ('ONEPLUS', 'one plus'), ('SONY', 'sony')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, default=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
