# Generated by Django 3.2 on 2023-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231128_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
