# Generated by Django 3.2 on 2023-12-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_ordered_date'),
        ('core', '0007_orderitem_tracking_number'),
    ]

    operations = [
    ]
